# Generated by Django 4.2 on 2023-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentdatafixed_delete_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chicken', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdatafixed',
            name='Year',
            field=models.CharField(max_length=50),
        ),
    ]
